<template>
  <v-col>
    <v-text-field
      label="Email"
      hide-details
      required
    ></v-text-field>
    <v-text-field
      class="mt-5"
      label="Password"
      hide-details
      required
      type="password"
    ></v-text-field>
    <v-btn 
      color="#AED2FF" 
      block 
      class="mt-5"
    >
    Войти
    </v-btn>
  </v-col>
</template>